; PlatformIO Project Configuration File — WIRELESS version
[env:adafruit_feather_esp32s3]
platform = espressif32
board = adafruit_feather_esp32s3
framework = arduino

upload_port = COM3
monitor_port = COM3
monitor_speed = 115200

lib_deps =
  adafruit/Adafruit AS7343@^1.1.0
  adafruit/Adafruit BusIO

build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
